# Language doesn't matter in this case, since we are building in Docker
language: erlang

otp_release:
  - 21.0

notifications:
  email:
    recipients:
      - mail@radupopescu.net
    on_success: change
    on_failure: always

script:
  - rebar3 as test dialyzer
  - rebar3 as test ct
  - rebar3 as prod release
  - rebar3 as prod tar
